const DistrictEnums = [
  "Orchard",
  "Somerset",
  "River Valley",
  "Tanglin",
  "Bukit Timah",
  "Holland",
  "Newton",
  "Novena",
  "Dunearn",
  "Watten",
  "Boat Quay",
  "Raffles Place",
  "Marina Downtown",
  "Suntec City",
  "Shenton Way",
  "Tanjong Pagar",
  "Sentosa",
  "City Hall",
  "Bugis",
  "Marina South",
  "Chinatown",
  "Queenstown",
  "Alexandra",
  "Tiong Bahru",
  "Harbourfront",
  "Keppel",
  "Telok Blangah",
  "Buona Vista",
  "Dover",
  "Pasir Panjang",
  "Fort Canning",
  "Rochor",
  "Little India",
  "Farrer Park",
  "Balestier",
  "Whampoa",
  "Toa Payoh",
  "Boon Keng",
  "Bendemeer",
  "Kampong Bugis",
  "Potong Pasir",
  "Bidadari",
  "MacPherson",
  "Upper Aljunied",
  "Geylang",
  "Dakota",
  "Paya Lebar Central",
  "Eunos",
  "Ubi",
  "Aljunied",
  "Tanjong Rhu",
  "Amber",
  "Meyer",
  "Katong",
  "Dunman",
  "Joo Chiat",
  "Marine Parade",
  "Bishan",
  "Thomson",
  "Clementi",
  "West Coast",
  "Kembangan",
  "Kaki Bukit",
  "Telok Kurau",
  "Siglap",
  "Frankel",
  "Bedok",
  "Upper East Coast",
  "Bayshore",
  "Tanah Merah",
  "Upper Changi",
  "Flora Drive",
  "Loyang",
  "Changi",
  "Tampines",
  "Pasir Ris",
  "Punggol",
  "Sengkang",
  "Hougang",
  "Kovan",
  "Serangoon",
  "Lorong Ah Soo",
  "Ang Mo Kio",
  "Upper Bukit Timah",
  "Ulu Pandan",
  "Clementi Park",
  "Jurong East",
  "Jurong West",
  "Boon Lay",
  "Hillview",
  "Bukit Panjang",
  "Bukit Batok",
  "Choa Chu Kang",
  "Kranji",
  "Lim Chu Kang",
  "Sungei Gedong",
  "Tengah",
  "Woodlands",
  "Admiralty",
  "Lentor",
  "Springleaf",
  "Mandai",
  "Yishun",
  "Sembawang",
  "Seletar",
  "Seletar Hill",
  "Sengkang West",
];

export default DistrictEnums;
